/**
 * ResQMesh — Mangaluru Flood Scenario Fixtures
 * Incident and resource values are simulated; runtime signatures are generated by Web Crypto.
 */

const INITIAL_SOS_DATA = [
  {
    id: 'SOS-1042',
    priority: 'critical',
    title: 'Family of 4 trapped · Ullal Bypass Rd',
    loc: 'Ullal · Nethravathi overflow',
    time: '10:42 · simulated',
    x: 24,
    y: 72,
    coordinates: [12.8152, 74.8584],
    hops: 3,
    ttl: 7,
    packet: '0x8F9A2',
    status: 'Relaying',
    people: 4,
    type: 'trapped',
    ed25519: null,
    cap: {
      event: 'Flash Flood / Trapped Persons',
      urgency: 'Immediate',
      severity: 'Extreme',
      certainty: 'Observed',
      headline: '4 persons trapped due to sudden Nethravathi river overflow in Ullal',
      areaDesc: 'Ullal Bypass Road near bridge marker 4'
    },
    trust: {
      source: "Neha's Phone · BLE relay",
      reported: '28 Aug · 10:42',
      corrob: 4,
      sig: 'Signature pending',
      fresh: 92,
      conf: 94,
      conflict: false
    }
  },
  {
    id: 'SOS-1043',
    priority: 'critical',
    title: 'Elderly woman, no medication · Kadri Hills',
    loc: 'Kadri Hills · Mangaluru',
    time: '10:39 · simulated',
    x: 49,
    y: 52,
    coordinates: [12.892, 74.866],
    hops: 2,
    ttl: 9,
    packet: '0x2C114',
    status: 'Delivered',
    people: 1,
    type: 'medical',
    ed25519: null,
    cap: {
      event: 'Medical Emergency / Oxygen Dependent',
      urgency: 'Immediate',
      severity: 'Severe',
      certainty: 'Observed',
      headline: 'Elderly patient requiring vital medication and oxygen check',
      areaDesc: 'Kadri Hills, Residential block C'
    },
    trust: {
      source: 'Volunteer Bike · relay',
      reported: '28 Aug · 10:39',
      corrob: 1,
      sig: 'Signature pending',
      fresh: 81,
      conf: 76,
      conflict: false
    }
  },
  {
    id: 'SOS-1044',
    priority: 'high',
    title: 'Water rising near riverbank',
    loc: 'Nethravathi River · Ullal',
    time: '10:33 · simulated',
    x: 31,
    y: 65,
    coordinates: [12.838, 74.858],
    hops: 4,
    ttl: 5,
    packet: '0x77AE1',
    status: 'Relaying',
    people: 8,
    type: 'trapped',
    ed25519: null,
    cap: {
      event: 'Rising Floodwaters',
      urgency: 'Expected',
      severity: 'Severe',
      certainty: 'Observed',
      headline: 'Rapid flood swell at Nethravathi riverbank settlement',
      areaDesc: 'Nethravathi Riverbank Lower Enclave'
    },
    trust: {
      source: 'NDRF Field Vehicle · Surathkal',
      reported: '28 Aug · 10:33',
      corrob: 2,
      sig: 'Signature pending',
      fresh: 70,
      conf: 83,
      conflict: false
    }
  },
  {
    id: 'SOS-1045',
    priority: 'high',
    title: 'Medical evacuation · Ullal coast',
    loc: 'Ullal Beach Road · Mangaluru',
    time: '10:28 · simulated',
    x: 19,
    y: 78,
    coordinates: [12.81, 74.857],
    hops: 1,
    ttl: 8,
    packet: '0x9B203',
    status: 'Delivered',
    people: 2,
    type: 'medical',
    ed25519: null,
    cap: {
      event: 'Medical Evacuation',
      urgency: 'Immediate',
      severity: 'Severe',
      certainty: 'Observed',
      headline: 'Injured fisherman needing coastal evacuation to Wenlock Hospital',
      areaDesc: 'Ullal Beach Road boat landing pier'
    },
    trust: {
      source: "Neha's Phone · BLE relay",
      reported: '28 Aug · 10:28',
      corrob: 1,
      sig: 'Signature pending',
      fresh: 65,
      conf: 71,
      conflict: false
    }
  },
  {
    id: 'SOS-1046',
    priority: 'medium',
    title: 'Flood access blocked · NH-66',
    loc: 'NH-66 · Mangaluru',
    time: '10:20 · simulated',
    x: 56,
    y: 61,
    coordinates: [12.84, 74.852],
    hops: 2,
    ttl: 6,
    packet: '0x4E872',
    status: 'Delivered',
    people: 0,
    type: 'other',
    ed25519: null,
    cap: {
      event: 'Infrastructure Obstruction',
      urgency: 'Expected',
      severity: 'Moderate',
      certainty: 'Likely',
      headline: 'Debris and flash flood water across NH-66 northbound lanes',
      areaDesc: 'NH-66 KM marker 14.2'
    },
    trust: {
      source: 'Volunteer Bike · relay',
      reported: '28 Aug · 10:20',
      corrob: 3,
      sig: 'Signature pending',
      fresh: 58,
      conf: 88,
      conflict: true
    }
  },
  {
    id: 'SOS-1040',
    priority: 'resolved',
    title: 'Evacuation completed · Surathkal',
    loc: 'Surathkal · Mangaluru',
    time: '09:58 · simulated',
    x: 70,
    y: 24,
    coordinates: [13.006, 74.792],
    hops: 2,
    ttl: 0,
    packet: '0x11FA0',
    status: 'Resolved',
    people: 3,
    type: 'other',
    ed25519: null,
    cap: {
      event: 'Shelter Transfer Completed',
      urgency: 'Past',
      severity: 'Minor',
      certainty: 'Observed',
      headline: '3 individuals successfully relocated to Surathkal relief camp',
      areaDesc: 'Surathkal coastal school shelter'
    },
    trust: {
      source: 'NDRF Field Vehicle · Surathkal',
      reported: '28 Aug · 09:58',
      corrob: 2,
      sig: 'Signature pending',
      fresh: 40,
      conf: 90,
      conflict: false
    }
  }
];

const OTHER_MARKERS = [
  { t: 'Ambulance 04 · available (simulated)', c: 'var(--info)', x: 45, y: 51, coordinates: [12.854, 74.846], l: 'A' },
  { t: 'NDRF Field Vehicle · Surathkal (simulated)', c: 'var(--info)', x: 70, y: 24, coordinates: [13.006, 74.792], l: 'N' },
  { t: 'Wenlock District Hospital · capacity simulated', c: 'var(--info)', x: 47, y: 43, coordinates: [12.87, 74.843], l: 'H' },
  { t: 'Collector Office · command HQ', c: 'var(--warn)', x: 82, y: 42, coordinates: [12.876, 74.845], l: 'Q' },
  { t: 'Ullal Beach Road · flooding simulated', c: 'var(--warn)', x: 20, y: 75, coordinates: [12.82, 74.854], l: '×' },
  { t: "Neha's Phone · BLE relay", c: 'var(--accent)', x: 34, y: 60, coordinates: [12.827, 74.855], l: 'R' },
  { t: 'Volunteer Bike · relay', c: 'var(--accent)', x: 51, y: 63, coordinates: [12.854, 74.85], l: 'B' }
];

const MESH_NODES = [
  { title: 'Victim Phone · Ullal', short: 'Victim phone · Ullal', label: 'Ullal', narration: 'Victim phone near Ullal signs and queues the Ed25519 SOS packet.' },
  { title: "Neha's Phone · BLE relay", short: "Neha's phone · BLE", label: 'Neha · BLE', narration: "Neha's phone detects the Bluetooth beacon and forwards the packet hop-by-hop." },
  { title: 'Volunteer Bike · Relay', short: 'Volunteer bike · relay', label: 'Volunteer bike', narration: 'Volunteer bike acts as a mobile DTN data-mule across the isolated gap.' },
  { title: 'NDRF Field Vehicle · Surathkal', short: 'NDRF vehicle · Surathkal', label: 'NDRF · Surathkal', narration: 'NDRF field vehicle with emergency satellite uplink receives the bundle.' },
  { title: 'District Collector Office · HQ', short: 'Collector Office · HQ', label: 'Collector HQ', narration: "Collector's office syncs the incident into the master digital public infrastructure." }
];

const MESH_POSITIONS = [[70, 196], [225, 153], [385, 106], [550, 68], [710, 34]];

function fingerprintFor(s) {
  return `${s.type}|${s.title.trim().toLowerCase()}|${s.loc.trim().toLowerCase()}`;
}

window.INITIAL_SOS_DATA = INITIAL_SOS_DATA;
window.OTHER_MARKERS = OTHER_MARKERS;
window.MESH_NODES = MESH_NODES;
window.MESH_POSITIONS = MESH_POSITIONS;
window.fingerprintFor = fingerprintFor;
